CREATE TABLE STATES(
ST_CODE         NUMBER(1,0),
ST_NAME         NVARCHAR2(10)
)TABLESPACE USERS;

CREATE TABLE CATEGORIES(
CA_CODE         NCHAR(2),
CA_NAME         NVARCHAR2(100)
)TABLESPACE USERS;

CREATE TABLE GOODS(
GO_CODE         NCHAR(5),
GO_NAME         NVARCHAR2(20),
GO_COST         NUMBER(7,0),
GO_PRICE        NUMBER(7,0),
GO_STOCKS       NUMBER(3,0),
GO_DISCOUNT     NUMBER(2,0),
GO_CACODE       NCHAR(2),
GO_STCODE       NUMBER(1,0)
)TABLESPACE USERS;

/*CONSTRAINTS : ALTER TABLE [TAB_NAME] [ADD|DROP] [CONSTRAINT] [CONST_NAME] [CONST_TYPE([COLUM])]*/
ALTER TABLE CATEGORIES ADD CONSTRAINT CA_CODE_PK PRIMARY KEY(CA_CODE);
ALTER TABLE STATES ADD CONSTRAINT ST_CODE_PK PRIMARY KEY(ST_CODE);
ALTER TABLE GOODS ADD CONSTRAINT GO_CODE_PK PRIMARY KEY(GO_CODE);
--CHECK
SELECT*FROM SW22_CONSTRAINTS;
ALTER TABLE CATEGORIES DROP CONSTRAINT CA_CODE_PK;
--제약조건의 활용
INSERT INTO CATEGORIES(CA_CODE, CA_NAME) VALUES('S1', '비스켓류');
INSERT INTO CATEGORIES(CA_CODE, CA_NAME) VALUES('S1', '쿠키');
INSERT INTO CATEGORIES(CA_CODE, CA_NAME) VALUES('S2', '비스켓류');
--DATA CHECK
SELECT*FROM SW22.CATEGORIES;
ROLLBACK;
--NOT NULL 제약조건
ALTER TABLE SW22.CATEGORIES
--MODIFY CA_NAME NOT NULL;
MODIFY CA_NAME NULL;
-- NOT NULL 활용
INSERT INTO CATEGORIES(CA_CODE, CA_NAME) VALUES('S1', '비스켓류');
 INSERT INTO CATEGORIES(CA_CODE, CA_NAME) VALUES('S2', NULL);  --> NOT NULL 제약에 위배
 INSERT INTO CATEGORIES(CA_CODE, CA_NAME) VALUES('S2', NULL);  --> NOT NULL 제약 삭제
--DATA CHECK
SELECT*FROM SW22.CATEGORIES;
--Null --> NOT NULL
ALTER TABLE SW22.CATEGORIES
MODIFY CA_NAME NOT NULL;
--> : 이미 해당 컬럼에 NULL 데이터가 존재하므로 변경 불가
 -- 문제가 되는 레코드를 삭제 하거나 NULL데이터를 업데이트 
 DELETE FROM CATEGORIES WHERE CA_CODE = 'S2';
ALTER TABLE CATEGORIES DROP CONSTRAINT CA_NAME;
COMMIT;
--CONSTRAINTS
ALTER TABLE SW22.STATES
ADD CONSTRAINT ST_CODE_PK PRIMARY KEY(ST_CODE);
ALTER TABLE SW22.STATES
MODIFY ST_NAME NOT NULL;

ALTER TABLE SW22.GOODS
MODIFY GO_NAME NOT NULL
MODIFY GO_CACODE NOT NULL
MODIFY GO_STCODE NOT NULL
MODIFY GO_PRICE DEFAULT 0 NOT NULL --DEFAULT 가 NOT NULL앞에 와야한다.
MODIFY GO_COST DEFAULT 0 NOT NULL
MODIFY GO_STOCKS DEFAULT 0 NOT NULL;
ALTER TABLE SW22.GOODS
MODIFY GO_DISCOUNT DEFAULT 0 NOT NULL;

--DEFAULT
INSERT INTO GOODS(GO_CODE, GO_NAME,  GO_COST, GO_PRICE, GO_STOCKS, GO_DISCOUNT, GO_CACODE, GO_STCODE)
VALUES('10001', 'KKK', DEFAULT, 1000, DEFAULT, DEFAULT, 'S1', 1 );
SELECT * FROM GOODS;
/* 자기 소유의 테이블 조회 */
SELECT * FROM USER_TABLES;

SELECT * FROM USER_CONSTRAINTS;