CREATE TABLE CATEGORIES(
CAT_CODE        NCHAR(2),
CAT_NAME        NVARCHAR2(100)
)TABLESPACE USERS;

ALTER TABLE CATEGORIES ADD CONSTRAINT CAT_CODE_PK PRIMARY KEY(CAT_CODE);

INSERT INTO CATEGORIES(CAT_CODE, CAT_NAME) VALUES('S1', '비스켓류');
INSERT INTO CATEGORIES(CAT_CODE, CAT_NAME) VALUES('S2', '쿠키');

ALTER TABLE CATEGORIES MODIFY CAT_NAME NOT NULL

ALTER TABLE CATEGORIES ADD CONSTRAINT CAT_NAME_UK UNIQUE(CAT_NAME)

----------------------------------------------------------------------------------------------------------------------

CREATE TABLE STATS(
STAT_CODE       NUMBER(1,0),
STAT_NAME       NVARCHAR2(10)
)TABLESPACE USERS;

ALTER TABLE STATS ADD CONSTRAINT STAT_CODE_PK PRIMARY KEY(STAT_CODE);

ALTER TABLE STATS MODIFY STAT_NAME NOT NULL
INSERT INTO STATS(STAT_CODE, STAT_NAME) VALUES('1', '판매가능');
INSERT INTO STATS(STAT_CODE, STAT_NAME) VALUES('-1', '판매불가');

ALTER TABLE STATS ADD CONSTRAINT STAT_NAME_UK UNIQUE(STAT_NAME)

----------------------------------------------------------------------------------------------------------------------

CREATE TABLE PRODUCT(
PR_CODE           NCHAR(5),
PR_NAME          NVARCHAR2(20),
PR_COST           NUMBER(7,0),
PR_PRICE          NUMBER(7,0),
PR_STOCKS       NUMBER(3,0),
PR_DISCOUNT   NUMBER(2,0),
PR_CATCODE     NCHAR(2),
PR_STATCODE    NUMBER(1,0)
)TABLESPACE USERS;

ALTER TABLE PRODUCT ADD CONSTRAINT PR_CODE_PK PRIMARY KEY(PR_CODE);

ALTER TABLE PRODUCT
MODIFY PR_NAME NOT NULL
MODIFY PR_CODE NOT NULL
MODIFY PR_COST DEFAULT 0 NOT NULL
MODIFY PR_PRICE DEFAULT 0 NOT NULL
MODIFY PR_STOCKS DEFAULT 0 NOT NULL
MODIFY PR_DISCOUNT DEFAULT 0 NOT NULL
MODIFY PR_CATCODE NOT NULL
MODIFY PR_STATCODE NOT NULL;

ALTER TABLE PRODUCT
ADD CONSTRAINT PR_CATCODE_FK FOREIGN KEY(PR_CATCODE) REFERENCES CATEGORIES(CAT_CODE)
ADD CONSTRAINT PR_STATCODE_FK FOREIGN KEY(PR_STATCODE) REFERENCES STATS(STAT_CODE);

ALTER TABLE PRODUCT ADD CONSTRAINT PR_NAME_UK UNIQUE(PR_NAME)

ALTER TABLE DBA1JO.PRODUCT
ADD CONSTRAINT PR_STOCKS_CK CHECK(PR_STOCKS >= 0);

----------------------------------------------------------------------------------------------------------------------

CREATE TABLE CUSTOMER(

CU_CODE           NCHAR(5),
CU_NAME          NVARCHAR2(6),
CU_PHONE         NUMBER(11,0),
CU_RACODE       NCHAR(5)

)TABLESPACE USERS;

ALTER TABLE CUSTOMER
ADD CONSTRAINT CU_CODE_PK PRIMARY KEY(CU_CODE)

ALTER TABLE DBA1JO.CUSTOMER
ADD CONSTRAINT CU_PHONE_UK UNIQUE(CU_PHONE);

ALTER TABLE DBA1JO.CUSTOMER
ADD CONSTRAINT CU_RACODE_FK FOREIGN KEY(CU_RACODE) REFERENCES RANKS(RA_CODE);

ALTER TABLE DBA1JO.CUSTOMER
MODIFY CU_NAME NOT NULL
MODIFY CU_PHONE NOT NULL
MODIFY CU_RACODE NOT NULL;

INSERT INTO CUSTOMER(CU_CODE, CU_NAME, CU_PHONE, CU_RACODE)
VALUES('9999', '비회원고객', 00000000000, 'X')

----------------------------------------------------------------------------------------------------------------------

CREATE TABLE RANKS(

RA_CODE          NCHAR(5),
RA_RANKS        NVARCHAR2(6)

)TABLESPACE USERS;

ALTER TABLE RANKS 
ADD CONSTRAINT RA_CODE_PK PRIMARY KEY(RA_CODE)

ALTER TABLE DBA1JO.RANKS
MODIFY RA_RANKS NOT NULL

INSERT INTO RANKS(RA_CODE, RA_RANKS) VALUES('1', 'BRONZE');
INSERT INTO RANKS(RA_CODE, RA_RANKS) VALUES('2', 'SILVER');
INSERT INTO RANKS(RA_CODE, RA_RANKS) VALUES('3', 'GOLD');
INSERT INTO RANKS(RA_CODE, RA_RANKS) VALUES('X', '비회원');

----------------------------------------------------------------------------------------------------------------------

CREATE TABLE STORES(

SE_CODE             NCHAR(5),
SE_NAME             NVARCHAR2(20),
SE_OPEN             NUMBER(4,0),
SE_CLOSE            NUMBER(4,0)

)TABLESPACE USERS;

ALTER TABLE STORES
ADD CONSTRAINT SE_CODE_PK PRIMARY KEY(SE_CODE);

ALTER TABLE STORES
MODIFY SE_NAME NOT NULL
MODIFY SE_OPEN DEFAULT 0 NOT NULL
MODIFY SE_CLOSE DEFAULT 0 NOT NULL

----------------------------------------------------------------------------------------------------------------------

CREATE TABLE EMPLOYEE(

EM_SECODE       NCHAR(5),
EM_CODE           NCHAR(5),
EM_NAME          NVARCHAR2(4)

)TABLESPACE USERS;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT EM_SECODE_FK FOREIGN KEY(EM_SECODE) REFERENCES STORES(SE_CODE);

ALTER TABLE EMPLOYEE
MODIFY EM_SECODE NOT NULL
MODIFY EM_CODE NOT NULL
MODIFY EM_NAME NOT NULL

----------------------------------------------------------------------------------------------------------------------

CREATE TABLE POS(

POS_SECODE       NCHAR(5),
POS_CODE           NCHAR(5)

)TABLESPACE USERS;

ALTER TABLE POS
ADD CONSTRAINT POS_SECODE_FK FOREIGN KEY(POS_SECODE) REFERENCES STORES(SE_CODE);
ALTER TABLE POS
ADD CONSTRAINT POS_SECODE_CODE_PK PRIMARY KEY(POS_SECODE, POS_CODE);

ALTER TABLE POS
MODIFY POS_SECODE NOT NULL
MODIFY POS_CODE NOT NULL

----------------------------------------------------------------------------------------------------------------------

CREATE TABLE ORDERS(

OD_CODE             NCHAR(14),
OD_SECODE         NCHAR(3),
OD_PSCODE         NCHAR(2),
OD_CUCODE         NCHAR(4)
OD_STATES          NCHAR(1)

)TABLESPACE USERS;

/*
alter table [테이블명] add [컬럼명] [타입] [옵션];  컬럼추가하는방법

ex) alter table [테이블명] add [컬럼명] varchar(100) not null default '0'; 

*/
ALTER TABLE ORDERS
ADD CONSTRAINT OD_CODE_PSCODE_SECODE_PK PRIMARY KEY(OD_CODE, OD_PSCODE, OD_SECODE)

ALTER TABLE ORDERS
ADD CONSTRAINT OD_SECODE_FK FOREIGN KEY(OD_SECODE) REFERENCES STORES(SE_CODE);
ALTER TABLE ORDERS
ADD CONSTRAINT OD_CUCODE_FK FOREIGN KEY(OD_CUCODE) REFERENCES CUSTOMER(CU_CODE);
ALTER TABLE ORDERS
ADD CONSTRAINT OD_PSCODE_FK FOREIGN KEY(OD_SECODE, OD_PSCODE) REFERENCES POS(POS_SECODE, POS_CODE);

ALTER TABLE ORDERS
ADD OD_STATES NCHAR(1)



----------------------------------------------------------------------------------------------------------------------

CREATE TABLE ORDERDETAILS(

ODD_ODCODE          NCHAR(14),
ODD_SECODE           NCHAR(3),
ODD_PSCODE           NCHAR(2),
ODD_PRCODE           NCHAR(5),
ODD_QUANTITY        NUMBER(2,0) DEFAULT 1

)TABLESPACE USERS; 

ALTER TABLE ORDERDETAILS
ADD CONSTRAINT ODD_OD_SE_PS_PR_CODE_PK PRIMARY KEY(ODD_ODCODE, ODD_PSCODE, ODD_SECODE, ODD_PRCODE)

ALTER TABLE ORDERDETAILS
ADD CONSTRAINT ODD_OD_SE_PS_CODE_FK FOREIGN KEY(ODD_ODCODE, ODD_SECODE, ODD_PSCODE) REFERENCES ORDERS(OD_CODE,OD_SECODE,OD_PSCODE);

ALTER TABLE ORDERDETAILS
ADD CONSTRAINT ODD_PRCODE_FK FOREIGN KEY(ODD_PRCODE) REFERENCES PRODUCT(PR_CODE)

ALTER TABLE ORDERDETAILS
MODIFY ODD_QUANTITY NOT NULL;

COMMIT;

----------------------------------------------------------------------------------------------------------------------

SELECT * FROM PR
SELECT * FROM PS
SELECT * FROM "EM"
SELECT * FROM RA
SELECT * FROM CU
SELECT * FROM SE
SELECT * FROM CA
SELECT * FROM ST

GRANT SELECT, INSERT, UPDATE ON DBA1JO.PRODUCT TO DM21;
GRANT SELECT, INSERT, UPDATE ON DBA1JO.PRODUCT TO DH21;
GRANT SELECT, INSERT, UPDATE ON DBA1JO.PRODUCT TO SW22;
GRANT SELECT, INSERT, UPDATE ON DBA1JO.PRODUCT TO GJ21;

CREATE PUBLIC SYNONYM CA FOR DBA1JO.CATEGORIES;
CREATE PUBLIC SYNONYM SE  FOR DBA1JO.STORES;
CREATE PUBLIC SYNONYM "EM" FOR DBA1JO.EMPLOYEE;
CREATE PUBLIC SYNONYM ST FOR DBA1JO.STATS;
CREATE PUBLIC SYNONYM PS FOR DBA1JO.POS;
CREATE PUBLIC SYNONYM RA FOR DBA1JO.RANKS;
CREATE PUBLIC SYNONYM CU FOR  DBA1JO.CUSTOMER;
CREATE PUBLIC SYNONYM PR FOR DBA1JO.PRODUCT;

----------------------------------------------------------------------------------------------------------------------

