/*  DATABASE LANGUAGE
    - DDL(DATA DEFINITION LANGUAGE)
        : 정의어 == 틀을 만든다.
        : CREATE [OBJECT] [OBJ_NAME]
        : ALTER [OBJECT] [OBJ_NAME] 
        : DROP [OBJECT] [OBJ_NAME]
    - DML(DATA MULTIPULATION LANGUAGE)
    - DCL(DATA CONTROL LANGUAGE)
        : PRIVILEIGE(권한 관리), 
           GRANT [PRIV_NAME], ..., [PRIV_NAME]  TO [USER_NAME];
           REVOKE [PRIV_NAME], ..., [PRIV_NAME]  FROM [USER_NAME];
        : TRANSACTION(트랜잭션 관리)
    - QL(QUERY LANGUAGE)
*/
/* User Creation 
    -- SYNTAX
    *  CREATE USER [USER_NAME]
    *  IDENTIFIED BY "[PASSWORD]"
    *- DEFAULT TABLESPACE [TBS_NAME]
       TEMPORARY TABLESPACE [TBS_NAME]
       QUOTA [[NUMBER [K|M|G]] | UNLIMITED] ON [TBS_NAME]
       
  실습 1 
   각 팀의 DBA가 팀원들이 사용할 계정을 생성
   - MEMBER1 / HOONZZANG / 1234
   - MEMBER2 / ZZANG / 1234
   - MEMBER3 / HOON / 1234
   - MEMBER4 / ZZANGZZANG / 1234
*/


CREATE USER GJ21
IDENTIFIED BY "1234"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO GJ21;

CREATE USER DM21
IDENTIFIED BY "1234"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO DM21;

CREATE USER DH21
IDENTIFIED BY "1234"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO DH21;
/*아이디 생성*/
CREATE USER SW21
/* 비밀번호 생성*/
IDENTIFIED BY "1234"
/*특별히 따로 지정하지 않으면 USERS TABLESPACE를 사용하겠다.*/
DEFAULT TABLESPACE USERS
/*저장용량에 제한을 두지 않겠다.*/
QUOTA UNLIMITED ON USERS;
/*CREATE SESSION이라는 권한을 부여*/
GRANT CREATE SESSION TO SW21;
/*CREATE SESSION이라는 권한을 박탈*/
REVOKE CREATE SESSION FROM GJ21;
/*GJ21 아이디 삭제*/
DROP USER GJ21;

DROP USER SW21;
