/* Oracle PL/SQL
    SQL : TEXT --> ORACLE : PARSING --> COMPILE  --> EXCUTION
 - Block 구조  >>   ORACLE :: COMPILE 까지 진행되어 있음 :: PARAMETER값만 제외
 - 변수 사용 : 변수 정의, 사용
 - 제어 구문 : IF
 - 반복 구문 : LOOP, WHILE, FOR
 
 - PL/SQL의 Block 구조
   선언부 :: 필수 :: DECLARE  :: BLOCK 내에서 사용하고자 하는 변수 선언
                 -- 변수, 상수, CURSOR, 사용자예외처리에 대한 정의
   실행부 :: 필수 :: BEGIN ~ END
                 -- SQL(DML + QL)
                 -- 조건문, 반복문
   예외절 :: 선택 :: EXCEPTION :: 실행부 안에 포함
                 -- 예외에 대한 처리
 - PL/SQL의 Block 유형 []는 생략가능하다는 소리.
   ANONYMOUS BLOCK :: BLOCK에 대한 이름X : 1회만 실행
   [DECLARE]
   BEGIN
     실행구문;
    [EXEPTION]
   END;
   
   PROCEDURE BLOCK :: BLOCK에 대한 이름O : 재활용 가능 : PARAMETER
                   :: 엄밀히 말하면 리턴은 없지만 리턴과비슷하게 기능하게 만들수있다.
    SQL에 대한 실행
    
    PROCEDURE [PROC_NAME] IS
     [DECLARE]
    BEGIN
     실행구문;
    [EXEPTION]
    END;
   
   FUNCTION BLOCK  :: BLOCK에 대한 이름O : 재활용 가능 : RETURN, PARAMETER
                   :: 컬럼의 값을 이용하여 새로운 데이터를 만들 때
                   :: 리턴타입이 있는 경우 
    FUNCTION [FUNC_NAME] 
    RETURN DATA_TYPE
    IS
     [DECLARE]
    BEGIN
     실행구문;
    [EXEPTION]
    END;
   ++ TRIGGER BLOCK
*/
/*메뉴 등록 PROCEDURE*/
CREATE OR REPLACE PROCEDURE REGCATEGORY
/*IN OUT INOUT PARAMETER(파라미터 타입들)*/
(CCODE IN NCHAR, CNAME IN NVARCHAR2 )/*파라미터 작성한거*/
IS


BEGIN
INSERT INTO CA(CAT_CODE,CAT_NAME) VALUES(CCODE, CNAME);
COMMIT;
END;

--PROCEDURE CALL
EXECUTE REGCATEGORY('A2', '프로시저테스트13');

CREATE OR REPLACE PROCEDURE UPDCATEGORY
/*IN OUT INOUT PARAMETER(파라미터 타입들)*/
(CCODE IN NCHAR, CNAME IN NVARCHAR2 )/*파라미터 작성한거*/
IS


BEGIN
UPDATE CA SET CAT_CODE = 'A8' WHERE CAT_CODE = 'A2';
COMMIT;
END;

EXECUTE UPDCATEGORY('A8', '프로시저테스트13');
--------------------------------------------------
CREATE OR REPLACE PROCEDURE REGSTATE
(STCODE IN NUMBER, STNAME IN NVARCHAR2 )
IS


BEGIN
INSERT INTO ST(STAT_CODE,STAT_NAME) VALUES(STCODE, STNAME);
COMMIT;
END;

EXECUTE REGSTATE('4', '프로시저테스트상태');
---------------------------------------------------------
CREATE OR REPLACE PROCEDURE UPDSTATE
(STCODE IN NUMBER, STNAME IN NVARCHAR2 )
IS


BEGIN

UPDATE ST SET STAT_NAME = '9999' WHERE STAT_CODE = '4';
COMMIT;
END;

EXECUTE UPDSTATE('4', '프로시저테스트상태');
-----------------------------------------------------------------
/* PL/SQL DATA TYPE
   1. SCALAR >> 하나의 데이터 타입
    [VAR_NAME]  [DATA_TYPE]  [:= INIT_VALUE];
    %TYPE_________
    [VAR_NAME]     [TAB_NAME.COL_NAME]%TYPE
    
   2. COMPLEX >> 여러개의 데이터 타입의 묶음
   %ROWTYPE_________
   [VAR_NAME]    [TAB_NAME]%ROWTYPE
   
   
*** DBMS_OUTPUT.PUT_LINE
*/

--CA 테이블의 특정 레코드를 출력 :: WHERE [PK 설정 컬럼]
CREATE OR REPLACE PROCEDURE GETCATEGORY(
 CCODE IN CA.CAT_CODE%TYPE
) IS
    CACODE CA.CAT_CODE%TYPE;
    CANAME CA.CAT_NAME%TYPE;

BEGIN
    DBMS_OUTPUT.ENABLE;
    SELECT CAT_CODE, CAT_NAME INTO CACODE, CANAME FROM CA WHERE CAT_CODE = CCODE;
    
    DBMS_OUTPUT.PUT_LINE('CACODE : ' || CACODE);
    DBMS_OUTPUT.PUT_LINE('CACODE : ' || CANAME);
END;
SET SERVEROUTPUT ON;

EXECUTE GETCATEGORY('A8');
-----------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GETCATEGORY2(
 CCODE IN CA.CAT_CODE%TYPE
) IS
    CATEGORIES CA%ROWTYPE;

BEGIN
    DBMS_OUTPUT.ENABLE;
    SELECT CAT_CODE, CAT_NAME INTO CATEGORIES.CAT_CODE, CATEGORIES.CAT_NAME FROM CA WHERE CAT_CODE = CCODE;
    
    DBMS_OUTPUT.PUT_LINE('CACODE : ' || CATEGORIES.CAT_CODE);
    DBMS_OUTPUT.PUT_LINE('CANAME : ' || CATEGORIES.CAT_NAME);
END;


EXECUTE GETCATEGORY('A8');
----------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GETSTATE(
 SCODE IN ST.STAT_CODE%TYPE
) IS
    STCODE ST.STAT_CODE%TYPE;
    STNAME ST.STAT_NAME%TYPE;

BEGIN
    DBMS_OUTPUT.ENABLE;
    SELECT STAT_CODE, STAT_NAME INTO STCODE, STNAME FROM ST WHERE STAT_CODE = SCODE;
    
    DBMS_OUTPUT.PUT_LINE('STCODE : ' || STCODE);
    DBMS_OUTPUT.PUT_LINE('STNAME : ' || STNAME);
END;
SET SERVEROUTPUT ON;

EXECUTE GETSTATE('4');
-----------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GETSTATE2(
 SCODE IN ST.STAT_CODE%TYPE
) IS
    STATES ST%ROWTYPE;

BEGIN
    DBMS_OUTPUT.ENABLE;
    SELECT STAT_CODE, STAT_NAME INTO STATES.STAT_CODE, STATES.STAT_NAME FROM ST WHERE STAT_CODE = SCODE;
    
    DBMS_OUTPUT.PUT_LINE('STCODE : ' || STATES.STAT_CODE);
    DBMS_OUTPUT.PUT_LINE('STNAME : ' || STATES.STAT_NAME);
END;
--TABLE_TYPE---------------------------------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GETCA_TABLE IS
    TYPE CACODE IS TABLE OF CA.CAT_CODE%TYPE INDEX BY BINARY_INTEGER;
    TYPE CANAME IS TABLE OF NVARCHAR2(100) INDEX BY BINARY_INTEGER;
  
  CCODE CACODE;
  CNAME CANAME;  
  
  IDX BINARY_INTEGER :=0;
BEGIN
    DBMS_OUTPUT.ENABLE;
    FOR CALIST IN(SELECT CAT_CODE, CAT_NAME FROM CA) LOOP
    CCODE(IDX):=CALIST.CAT_CODE;
    CNAME(IDX):=CALIST.CAT_NAME;
    IDX:=IDX+1;
    END LOOP;
    
    FOR IDX2 IN 0..IDX-1 LOOP
     DBMS_OUTPUT.PUT_LINE('분류코드 : '||CCODE(IDX2));
     DBMS_OUTPUT.PUT_LINE('분류이름 : '||CNAME(IDX2));
    END LOOP;

END;
EXECUTE GETCA_TABLE();
---TABLE_TYPE-------------------------------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GETPRCA_TABLE IS
    TYPE PRCODE IS TABLE OF PR.PR_CODE%TYPE INDEX BY BINARY_INTEGER;
    TYPE PRNAME IS TABLE OF NVARCHAR2(20) INDEX BY BINARY_INTEGER;
    TYPE PRCOST IS TABLE OF PR.PR_COST%TYPE INDEX BY BINARY_INTEGER;
    TYPE PRPRICE IS TABLE OF PR.PR_PRICE%TYPE INDEX BY BINARY_INTEGER;
    TYPE PRSTOCKS IS TABLE OF PR.PR_STOCKS%TYPE INDEX BY BINARY_INTEGER;
    TYPE PRDISCOUNT IS TABLE OF PR.PR_DISCOUNT%TYPE INDEX BY BINARY_INTEGER;
    TYPE PRCATCODE IS TABLE OF PR.PR_CATCODE%TYPE INDEX BY BINARY_INTEGER;
    TYPE PRSTATCODE IS TABLE OF PR.PR_STATCODE%TYPE INDEX BY BINARY_INTEGER;
  
  PCODE PRCODE;
  PNAME PRNAME;
  PCOST PRCOST;
  PPRICE PRPRICE;
  PSTOCKS PRSTOCKS;
  PDISCOUNT PRDISCOUNT;
  PCATCODE PRCATCODE;
  PSTATCODE PRSTATCODE;
  
  IDX BINARY_INTEGER :=0;
BEGIN
    DBMS_OUTPUT.ENABLE;
    FOR PRLIST IN(SELECT PR_CODE, PR_NAME, PR_COST, PR_PRICE, PR_STOCKS, PR_DISCOUNT
    , PR_CATCODE, PR_STATCODE FROM PR) LOOP
    PCODE(IDX):=PRLIST.PR_CODE;
    PNAME(IDX):=PRLIST.PR_NAME;
    PCOST(IDX):=PRLIST.PR_COST;
    PPRICE(IDX):=PRLIST.PR_PRICE;
    PSTOCKS(IDX):=PRLIST.PR_STOCKS;
    PDISCOUNT(IDX):=PRLIST.PR_DISCOUNT;
    PCATCODE(IDX):=PRLIST.PR_CATCODE;
    PSTATCODE(IDX):=PRLIST.PR_STATCODE;
    IDX:=IDX+1;
    END LOOP;
    
    FOR IDX2 IN 0..IDX-1 LOOP
     DBMS_OUTPUT.PUT_LINE('상품코드 : '||PCODE(IDX2));
     DBMS_OUTPUT.PUT_LINE('상품이름 : '||PNAME(IDX2));
     DBMS_OUTPUT.PUT_LINE('상품원가 : '||PCOST(IDX2));
     DBMS_OUTPUT.PUT_LINE('상품가격 : '||PPRICE(IDX2));
     DBMS_OUTPUT.PUT_LINE('상품재고 : '||PSTOCKS(IDX2));
     DBMS_OUTPUT.PUT_LINE('상품할인율 : '||PDISCOUNT(IDX2));
     DBMS_OUTPUT.PUT_LINE('상품분류 : '||PCATCODE(IDX2));
     DBMS_OUTPUT.PUT_LINE('상품상태코드 : '||PSTATCODE(IDX2));
    END LOOP;

END;

EXECUTE GETPRCA_TABLE();
--RECORD_TYPE-------------------------------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GETCA_RECORD
    (CCODE IN CA.CAT_CODE%TYPE)
IS
    TYPE CA_RECORD IS RECORD
    (CACODE CA.CAT_CODE%TYPE, CANAME NVARCHAR2(100));
    CAT CA_RECORD;
BEGIN
    DBMS_OUTPUT.ENABLE;
    SELECT CAT_CODE, CAT_NAME INTO CAT.CACODE, CAT.CANAME FROM CA WHERE CAT_CODE = CCODE;
    DBMS_OUTPUT.PUT_LINE('분류코드 : ' || CAT.CACODE );
    DBMS_OUTPUT.PUT_LINE('분류네임 : ' || CAT.CANAME );
END;
EXECUTE GETCA_RECORD('S1');
--RECORD_TYPE------------------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GETST_RECORD
    (SCODE IN ST.STAT_CODE%TYPE)
IS
    TYPE ST_RECORD IS RECORD
    (STCODE ST.STAT_CODE%TYPE, STNAME ST.STAT_NAME%TYPE);
    STT ST_RECORD;
BEGIN
    DBMS_OUTPUT.ENABLE;
    SELECT STAT_CODE, STAT_NAME INTO STT.STCODE, STT.STNAME FROM ST WHERE STAT_CODE = SCODE;
    DBMS_OUTPUT.PUT_LINE('상태코드 : ' || STT.STCODE );
    DBMS_OUTPUT.PUT_LINE('상태이름 : ' || STT.STNAME );
END;
EXECUTE GETST_RECORD(-4);
----TABLE OF RECORD_TYPE(시트지 만든다고 생각해)------------------------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GETCA_TAB_REC
IS
    TYPE CA_TR IS TABLE OF CA%ROWTYPE INDEX BY BINARY_INTEGER;
    CALIST CA_TR;
    IDX BINARY_INTEGER:=0;
BEGIN
    DBMS_OUTPUT.ENABLE;
    FOR REC IN(SELECT CAT_CODE, CAT_NAME FROM CA)LOOP
    CALIST(IDX).CAT_CODE:=REC.CAT_CODE;
    CALIST(IDX).CAT_NAME:=REC.CAT_NAME;
    IDX:=IDX+1;
    END LOOP;

    FOR CNT IN 0..IDX-1 LOOP
        DBMS_OUTPUT.PUT_LINE('분류코드 : '|| CALIST(CNT).CAT_CODE);
        DBMS_OUTPUT.PUT_LINE('분류네임 : '|| CALIST(CNT).CAT_NAME);    
    END LOOP;

END;
EXECUTE GETCA_TAB_REC;
--TABLE OF RECORD_TYPE 과제--------------------------------------------------------------------------------------------------- 
CREATE OR REPLACE PROCEDURE GETPRCAST_TAB_REC(PPPCODE IN PR.PR_CODE%TYPE)

IS
    TYPE PRCAST_RECORD IS RECORD
    (PRCODE PR.PR_CODE%TYPE,PRNAME PR.PR_NAME%TYPE
    , PRPRICE PR.PR_PRICE%TYPE, CANAME CA.CAT_NAME%TYPE, 
    STNAME ST.STAT_NAME%TYPE);
    TYPE PRCAST_TR IS TABLE OF PRCAST_RECORD INDEX BY BINARY_INTEGER;
    
    PRCASTLIST PRCAST_TR;
    IDX BINARY_INTEGER:=0;
BEGIN
    DBMS_OUTPUT.ENABLE;
    FOR REC IN(SELECT PR.PR_CODE AS RPCODE, 
    PR.PR_NAME AS RPNAME, PR_PRICE AS RPPRICE,
    CA.CAT_NAME AS RCNAME, ST.STAT_NAME AS RSNAME 
        FROM PR INNER JOIN CA ON PR.PR_CATCODE = CA.CAT_CODE
                INNER JOIN ST ON PR.PR_STATCODE = ST.STAT_CODE
                WHERE PR.PR_CODE = PPPCODE) LOOP
    
    PRCASTLIST(IDX).PRCODE:=REC.RPCODE;
    PRCASTLIST(IDX).PRNAME:=REC.RPNAME;
    PRCASTLIST(IDX).PRPRICE:=REC.RPPRICE;
    PRCASTLIST(IDX).CANAME:=REC.RCNAME;
    PRCASTLIST(IDX).STNAME:=REC.RSNAME;
    IDX:=IDX+1;
    END LOOP;
    FOR CNT IN 0..IDX-1 LOOP
        DBMS_OUTPUT.PUT_LINE('상품코드 : '|| PRCASTLIST(CNT).PRCODE);
        DBMS_OUTPUT.PUT_LINE('상품이름 : '|| PRCASTLIST(CNT).PRNAME);
        DBMS_OUTPUT.PUT_LINE('상품가격 : '|| PRCASTLIST(CNT).PRPRICE);
        DBMS_OUTPUT.PUT_LINE('분류 : '|| PRCASTLIST(CNT).CANAME);
        DBMS_OUTPUT.PUT_LINE('상태 : '|| PRCASTLIST(CNT).STNAME);

    END LOOP;

END;
EXECUTE GETPRCAST_TAB_REC('50001');
-------------------------저장
CREATE OR REPLACE PROCEDURE GETPRCAST_TAB_REC
IS
    TYPE PRCODE IS TABLE OF PR.PR_CODE%TYPE INDEX BY BINARY_INTEGER;
    TYPE PRNAME IS TABLE OF PR.PR_NAME%TYPE INDEX BY BINARY_INTEGER;
    TYPE PRPRICE IS TABLE OF PR.PR_PRICE%TYPE INDEX BY BINARY_INTEGER;
    TYPE CANAME IS TABLE OF CA.CA_NAME%TYPE INDEX BY BINARY_INTEGER;
    TYPE STNAME IS TABLE OF ST.STAT_NAME%TYPE INDEX BY BINARY_INTEGER;
    
    PCODE PRCODE;
    PNAME PRNAME;
    PPRICE PRPRICE;
    CNAME CANAME;
    SNAME STNAME;
    
    IDX BINARY_INTEGER:=0;
BEGIN
    DBMS_OUTPUT.ENABLE;
    SELECT PR.PR_CODE, PR.PR_NAME, PR_PRICE, CA.CA_NAME, ST.STAT_NAME
    FROM PR INNER JOIN CA ON PR.PR_CACODE = CA.CA_CODE
            INNER JOIN ST ON PR.PR_STCODE = ST.ST_CODE
    WHERE PR.PR_CODE = PCODE;
    FOR REC IN(SELECT CAT_CODE, CAT_NAME FROM CA)LOOP
    CALIST(IDX).CAT_CODE:=REC.CAT_CODE;
    CALIST(IDX).CAT_NAME:=REC.CAT_NAME;
    IDX:=IDX+1;
    END LOOP;
 FOR CNT IN 0..IDX-1 LOOP
        DBMS_OUTPUT.PUT_LINE('분류코드 : '|| CALIST(CNT).CAT_CODE);
        DBMS_OUTPUT.PUT_LINE('분류네임 : '|| CALIST(CNT).CAT_NAME);    
    END LOOP;

END;
-----------------------------------------------------------------------------------------------------------------------
/*--특정 고객에 대한 상품 판매 정보 출력------------------------------------------------
  주문코드  상품명  가격  수량  합계금액
  OD, ODD     GO   GO    ODD    F:GO*ODD
--------------------------------------------------------------------------------*/
CREATE OR REPLACE PROCEDURE GETGOODODD_TAB_REC(CUCODE IN OD.OD_CUCODE%TYPE)

IS
    TYPE GOODODD_RECORD IS RECORD
    (ODCODE ODD.ODD_ODCODE%TYPE,PRNAME PR.PR_NAME%TYPE
    , PRPRICE PR.PR_PRICE%TYPE, QUANTITY ODD.ODD_QUANTITY%TYPE, 
    TOTAL NUMBER(9,0));
    TYPE GOODODD_TR IS TABLE OF GOODODD_RECORD INDEX BY BINARY_INTEGER;
    
    GOODODDLIST GOODODD_TR;
    IDX BINARY_INTEGER:=0;
BEGIN
    DBMS_OUTPUT.ENABLE;
    FOR REC IN(SELECT ODD.ODD_ODCODE , 
    PR.PR_NAME , PR_PRICE ,
    ODD.ODD_QUANTITY   
        FROM ODD INNER JOIN PR ON ODD.ODD_PRCODE = PR.PR_CODE
                INNER JOIN OD ON ODD.ODD_ODCODE = OD.OD_CODE
                WHERE OD.OD_CUCODE = CUCODE) LOOP
    
    GOODODDLIST(IDX).ODCODE:=REC.ODD_ODCODE;
    GOODODDLIST(IDX).PRNAME:=REC.PR_NAME;
    GOODODDLIST(IDX).PRPRICE:=REC.PR_PRICE;
    GOODODDLIST(IDX).QUANTITY:=REC.ODD_QUANTITY;
    GOODODDLIST(IDX).TOTAL:=REC.PR_PRICE*REC.ODD_QUANTITY;
    IDX:=IDX+1;
    END LOOP;
    FOR CNT IN 0..IDX-1 LOOP
        DBMS_OUTPUT.PUT_LINE('주문코드 : '|| GOODODDLIST(CNT).ODCODE);
        DBMS_OUTPUT.PUT_LINE('상품이름 : '|| GOODODDLIST(CNT).PRNAME);
        DBMS_OUTPUT.PUT_LINE('상품가격 : '|| GOODODDLIST(CNT).PRPRICE);
        DBMS_OUTPUT.PUT_LINE('수량 : '|| GOODODDLIST(CNT).QUANTITY);
        DBMS_OUTPUT.PUT_LINE('합계금액 : '|| GOODODDLIST(CNT).TOTAL);

    END LOOP;

END;
EXECUTE GETGOODODD_TAB_REC('10011');
---------------------------------------------------------------------------------------
/*카테고리별 전체 상품에 판매정보 출력
--------------------------------------------------------------------------------
    카테고리명 CA.CAT_NAME
    판매액 PR.PR_PRICE * ODD.ODD_QUANTITY
    수익액 (PR.PR_PRICE - PR.PR_COST)* ODD.ODD_QUANTITY
--------------------------------------------------------------------------------    */
CREATE OR REPLACE PROCEDURE GETCAPRODD_TAB_REC(INPUTCATCODE IN CA.CAT_CODE%TYPE)

IS
    TYPE CAPRODD_RECORD IS RECORD
    ( CANAME CA.CAT_NAME%TYPE, 
    SALE NUMBER(9,0),MARGIN NUMBER(9,0));
    TYPE CAPRODD_TR IS TABLE OF CAPRODD_RECORD INDEX BY BINARY_INTEGER;
    
    CAPRODDLIST CAPRODD_TR;
    IDX BINARY_INTEGER:=0;
BEGIN
    DBMS_OUTPUT.ENABLE;
    FOR REC IN(SELECT CA.CAT_NAME AS CATNAME, SUM(PR.PR_PRICE*ODD.ODD_QUANTITY) AS SALE1,
              SUM((PR.PR_PRICE - PR.PR_COST)* ODD.ODD_QUANTITY) AS MARGIN1 
        FROM ODD INNER JOIN PR ON ODD.ODD_PRCODE = PR.PR_CODE
                INNER JOIN CA ON PR.PR_CATCODE = CA.CAT_CODE
                WHERE CA.CAT_CODE = INPUTCATCODE
                GROUP BY CA.CAT_NAME) LOOP
    
    CAPRODDLIST(IDX).CANAME:=REC.CATNAME;
    CAPRODDLIST(IDX).SALE:=REC.SALE1;
    CAPRODDLIST(IDX).MARGIN:=REC.MARGIN1;
    IDX:=IDX+1;
    END LOOP;
    FOR CNT IN 0..IDX-1 LOOP
        DBMS_OUTPUT.PUT_LINE('카테고리명 : '|| CAPRODDLIST(CNT).CANAME);
        DBMS_OUTPUT.PUT_LINE('판매액 : '|| CAPRODDLIST(CNT).SALE);
        DBMS_OUTPUT.PUT_LINE('수익액 : '|| CAPRODDLIST(CNT).MARGIN);
    END LOOP;
END;
SET SERVEROUTPUT ON;
EXECUTE GETCAPRODD_TAB_REC('S3');
-------------------------------------------------------------------------------------
-- GO<< GO_CODE :: SQL%FOUND 속성 확인
CREATE OR REPLACE PROCEDURE GETGOLIST(
 GOCODE    IN  PR.PR_CODE%TYPE

) IS
  PRNAME PR.PR_NAME%TYPE;
BEGIN
 SELECT PR_NAME INTO PRNAME FROM PR WHERE PR_CODE=GOCODE;
 
 --SQL%FOUND
 IF SQL%FOUND THEN
  DBMS_OUTPUT.PUT_LINE('데이터 존재함 : '||PRNAME);
  DBMS_OUTPUT.PUT_LINE('FETCHED RECORD : '||SQL%ROWCOUNT);
END IF;
 EXCEPTION
  WHEN NO_DATA_FOUND THEN
   DBMS_OUTPUT.PUT_LINE('데이터 없음');
   DBMS_OUTPUT.PUT_LINE('FETCHED RECORD : '||SQL%ROWCOUNT);
END;
   
EXECUTE  GETGOLIST('20001');
--명시적 커서의 활용---------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GOODSLIST
IS
--1. CURSOR DECLARE
    CURSOR GLIST IS
     SELECT CAT_CODE AS CCODE, CAT_NAME AS CNAME, COUNT(*) AS CNT
     FROM PR INNER JOIN CA ON PR.PR_CATCODE = CA.CAT_CODE GROUP BY CA.CAT_CODE, CAT_NAME;
BEGIN
--2. CURSOR OPEN & FETCH
    FOR REC IN GLIST LOOP
        DBMS_OUTPUT.PUT_LINE(REC.CNAME || ' : ' || REC.CNT);
    END LOOP;
    EXCEPTION
      WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR!!');
END;
SET SERVEROUTPUT ON;
EXECUTE GOODSLIST;
--명시적 커서의 활용 실전과제 1----------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GETGOODODDSLIST
IS
--1. CURSOR DECLARE
    CURSOR GETGOODODDSLIST IS
     SELECT ODD.ODD_ODCODE AS ODC, PR.PR_NAME AS PRN , PR_PRICE AS PRP, ODD.ODD_QUANTITY AS OQ   
        FROM ODD INNER JOIN PR ON ODD.ODD_PRCODE = PR.PR_CODE
                INNER JOIN OD ON ODD.ODD_ODCODE = OD.OD_CODE;
BEGIN
--2. CURSOR OPEN & FETCH
    FOR REC IN GETGOODODDSLIST LOOP
        DBMS_OUTPUT.PUT_LINE('주문코드 : '|| REC.ODC);
        DBMS_OUTPUT.PUT_LINE('상품이름 : '|| REC.PRN);
        DBMS_OUTPUT.PUT_LINE('상품가격 : '|| REC.PRP);
        DBMS_OUTPUT.PUT_LINE('수량 : '|| REC.OQ);
        DBMS_OUTPUT.PUT_LINE('합계금액 : '|| REC.PRP*REC.OQ);
    END LOOP;
    EXCEPTION
      WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR!!');
END;
SET SERVEROUTPUT ON;
EXECUTE GETGOODODDSLIST;
--커서에서 파라미터의 처리(커서 조차도 파라미터처리)---------------------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GOODSLIST
(CCODE IN CA.CAT_CODE%TYPE)
IS
--1. CURSOR DECLARE
    CURSOR GLIST(VCCODE CA.CAT_CODE%TYPE) IS
     SELECT CAT_CODE AS CCODE, CAT_NAME AS CNAME, COUNT(*) AS CNT
     FROM PR INNER JOIN CA ON PR.PR_CATCODE = CA.CAT_CODE
     WHERE CA.CAT_CODE = VCCODE
      GROUP BY CA.CAT_CODE, CAT_NAME;
     
BEGIN
--2. CURSOR OPEN & FETCH
    FOR REC IN GLIST(CCODE) LOOP
        DBMS_OUTPUT.PUT_LINE(REC.CNAME || ' : ' || REC.CNT);
    END LOOP;
    EXCEPTION
      WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR!!');
END;
SET SERVEROUTPUT ON;
EXECUTE GOODSLIST('S3');
--명시적 커서&커서에 파라미터 활용 실전과제 1----------------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GETGOODSLIST(CCODE IN CA.CAT_CODE%TYPE)

IS
    CURSOR GLIST(VCCODE CA.CAT_CODE%TYPE) IS
     SELECT CA.CAT_NAME AS CATNAME, SUM(PR.PR_PRICE*ODD.ODD_QUANTITY) AS SALE1,
              SUM((PR.PR_PRICE - PR.PR_COST)* ODD.ODD_QUANTITY) AS MARGIN1 
        FROM ODD INNER JOIN PR ON ODD.ODD_PRCODE = PR.PR_CODE
                INNER JOIN CA ON PR.PR_CATCODE = CA.CAT_CODE
                WHERE CA.CAT_CODE = VCCODE
                GROUP BY CA.CAT_NAME;
   
BEGIN
     FOR REC IN GLIST(CCODE) LOOP
        DBMS_OUTPUT.PUT_LINE('카테고리명 : '|| REC.CATNAME);
        DBMS_OUTPUT.PUT_LINE('판매액 : '|| REC.SALE1);
        DBMS_OUTPUT.PUT_LINE('수익액 : '|| REC.MARGIN1);
    END LOOP;
    EXCEPTION
      WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR!!');
END;
SET SERVEROUTPUT ON;
EXECUTE GETGOODSLIST('S3');